Implemented increasing speed
sakex/flappy-bird pull request #3
Opened 2021-07-23 15:43 UTC by Nereuxofficial

What do you think of these changes?
I'm not really sure if they are useful but without a speed increase the agents figure out how to play pretty fast and have endless runs...
Another way to increase the difficulty would be to narrow the gaps gradually

2021-07-23 22:10 UTC, sakex requested changes
Thanks for the idea! I think it could be interesting to look at, however I think it should be optional by adding a radio button on the front end if we want the speed to gradually increase. What do you think?

2021-07-23 22:10 UTC, sakex commented on src/game/game.rs
> +        let mut inputs = [(first_pipe.x * 2.0 - self.width) / self.width, 0., 0., self.get_speed()];
I think you should scale the speed input somehow, high values don't work well in the sigmoid function.

You could set a maximum speed for instance and give a percentage of it as input (scaled between - 1 and 1).

You could also not give it as input since it should not matter to reach the optimal solution

2021-07-24 09:45 UTC, Nereuxofficial commented
Thanks for the feedback! A checkbox sounds like a good idea. A maximum speed ensures that it never gets impossible. I haven't yet tested whether the speed as input makes any sense. I've just let it in there and now the input scales from -1.0 to 1.0 and you can decide whether to leave it in there

2021-07-26 00:11 UTC, sakex commented
@Nereuxofficial I see you did some other changes! Thanks for it, tell me when it's ready so I can merge and deploy

2021-07-26 12:11 UTC, Nereuxofficial commented
It's ready. I might change some things the following day but will only make a new PR when i did some new feature or major things

2021-07-26 19:12 UTC, sakex approved these changes

2021-07-26 19:13 UTC, merged

2021-07-26 19:13 UTC, sakex commented
@Nereuxofficial Merged